### ISSUE TITLE
Source distribution built by poetry is not working with pip.

### ISSUE THREAD

**Issue by linw1995** [linw1995/jsonpath#11]
Probably it's **intreehooks** causing this problem. Sdist (Source distribution) of **poetry** and **pdm** built by using the **intreehooks** is not working with pip too. The elder version 0.12.17 of poetry, without using **intreehooks**, is working well with pip.

**Comment by frostming** [comment]
I am also facing this problem and having a hard time debugging it. It seems a bug with pip 20.1 and isolated builds. I did the following things with your demo repo https://github.com/linw1995/sdist_install_error:

1. `pip install dist/sdist_install_error-0.1.0.tar.gz` - `No module named 'pip'`
2. `pip install .` which should have the same behavior as building from sdist - Successful
3. Change the backend to `poetry.masonry.api` and repeat step 1 - Successful

**Comment by linw1995** [comment]
@frostming  Poetry has an issue about the same problem we face. https://github.com/python-poetry/poetry/issues/2072
And it mentions a pull request that maybe resolve this problem. But I think it will not work.
https://github.com/python-poetry/poetry/pull/2090
I agree with you that it seems a bug from pip. And for now, I can not find any issue with this problem from pip repo.

**Comment by linw1995** [comment]
@frostming My bad. It seems to have a related issue. https://github.com/pypa/pip/issues/7248

**Comment by frostming** [comment]
It turns out that `build.py` is missing from the sdist. 🤦  That explains why `pip install .` succeeded.

After adding `include = ["build.py"]` to `pyproject.toml` and re build, everything goes fine.

**Comment by linw1995** [comment]
oops, you are right. my bad. It is hard to know what is wrong if you look at the pip install log. Thank for your help. So we are facing different problems?

**Comment by frostming** [comment]
你这个问题，有些巧合

1. 你没把`build.py`打包进去
2. pip调PEP 517构建的时候通过子进程运行`pip/_vendor/pep517/_in_process.py`这个脚本。运行脚本时会把**脚本父目录**加到`sys.path`.
3. intreehooks尝试去import `build`，本来应该找不到，报错的，但是因为`pip/_vendor/pep517/build.py`存在，所以就去导入这里了，然后这个脚本导入的前置依赖(`pip`)不满足，所以就出现了莫名其妙的报错。

**Comment by frostming** [comment]
>So we are facing different problems?

No, Pipenv lock does not respect PEP 517 requirements.https://github.com/pypa/pipenv/pull/4248

**Comment by linw1995** [comment]
> 你这个问题，有些巧合
> 
> 1. 你没把`build.py`打包进去
> 2. pip调PEP 517构建的时候通过子进程运行`pip/_vendor/pep517/_in_process.py`这个脚本。运行脚本时会把**脚本父目录**加到`sys.path`.
> 3. intreehooks尝试去import `build`，本来应该找不到报错的，但是因为`pip/_vendor/pep517/build.py`存在，所以就去导入这里了，然后这个脚本导入的前置依赖(`pip`)不满足，所以就出现了莫名其妙的报错。

这也太巧了……以后取名字要又长又复杂才行，以免踩这种坑 。
